// Code generated by protoc-gen-go.
// source: github.com/Rakanixu/smtp/srv/proto/smtp/smtp.proto
// DO NOT EDIT!

/*
Package go_micro_srv_smtp is a generated protocol buffer package.

It is generated from these files:
	github.com/Rakanixu/smtp/srv/proto/smtp/smtp.proto

It has these top-level messages:
	SendRequest
	SendResponse
*/
package go_micro_srv_smtp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SendRequest struct {
	Recipient []string `protobuf:"bytes,1,rep,name=recipient" json:"recipient,omitempty"`
	Subject   string   `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Body      string   `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *SendRequest) Reset()                    { *m = SendRequest{} }
func (m *SendRequest) String() string            { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()               {}
func (*SendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SendResponse struct {
}

func (m *SendResponse) Reset()                    { *m = SendResponse{} }
func (m *SendResponse) String() string            { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()               {}
func (*SendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SendRequest)(nil), "go.micro.srv.smtp.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "go.micro.srv.smtp.SendResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SMTP service

type SMTPClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error)
}

type sMTPClient struct {
	c           client.Client
	serviceName string
}

func NewSMTPClient(serviceName string, c client.Client) SMTPClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.smtp"
	}
	return &sMTPClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *sMTPClient) Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SMTP.Send", in)
	out := new(SendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SMTP service

type SMTPHandler interface {
	Send(context.Context, *SendRequest, *SendResponse) error
}

func RegisterSMTPHandler(s server.Server, hdlr SMTPHandler) {
	s.Handle(s.NewHandler(&SMTP{hdlr}))
}

type SMTP struct {
	SMTPHandler
}

func (h *SMTP) Send(ctx context.Context, in *SendRequest, out *SendResponse) error {
	return h.SMTPHandler.Send(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x0f, 0x4a, 0xcc, 0x4e, 0xcc, 0xcb, 0xac, 0x28, 0xd5,
	0x2f, 0xce, 0x2d, 0x29, 0xd0, 0x2f, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x72,
	0x81, 0x84, 0x1e, 0x98, 0x2f, 0x24, 0x98, 0x9e, 0xaf, 0x97, 0x9b, 0x99, 0x5c, 0x94, 0xaf, 0x07,
	0x54, 0xa3, 0x07, 0x92, 0x50, 0x8a, 0xe4, 0xe2, 0x0e, 0x4e, 0xcd, 0x4b, 0x09, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe1, 0xe2, 0x2c, 0x4a, 0x4d, 0xce, 0x2c, 0xc8, 0x4c, 0xcd, 0x2b,
	0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x49, 0x70, 0xb1, 0x17, 0x97, 0x26,
	0x65, 0xa5, 0x26, 0x97, 0x48, 0x30, 0x29, 0x30, 0x02, 0xe5, 0x60, 0x5c, 0x21, 0x21, 0x2e, 0x96,
	0xa4, 0xfc, 0x94, 0x4a, 0x09, 0x66, 0xb0, 0x30, 0x98, 0xad, 0xc4, 0xc7, 0xc5, 0x03, 0x31, 0xba,
	0xb8, 0x20, 0x3f, 0xaf, 0x38, 0xd5, 0x28, 0x90, 0x8b, 0x25, 0xd8, 0x37, 0x24, 0x40, 0xc8, 0x13,
	0x48, 0x03, 0xc5, 0x85, 0xe4, 0xf4, 0x30, 0x9c, 0xa3, 0x87, 0xe4, 0x16, 0x29, 0x79, 0x9c, 0xf2,
	0x10, 0x03, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xfe, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x25,
	0xb4, 0x33, 0x81, 0x0d, 0x01, 0x00, 0x00,
}
